CREATE DATABASE Find_Your_Doctor;

CREATE TABLE User_Details(
    User_ID INTEGER,   
    First_Name VARCHAR(200),
    Last_Name VARCHAR(200),
    Email_ID VARCHAR(200),
    Role_ID INTEGER,
    Experience_Level INTEGER DEFAULT 1,
    Date_Of_Birth DATE,
    Phone_Number VARCHAR(20),
    Created_Date DATE,
    Modified_Date Date,
    PRIMARY KEY (User_ID,Role_ID),
    FOREIGN KEY (Role_ID) REFERENCES Role_Mstr(Role_ID)
);

CREATE TABLE Role_Mstr(
    Role_ID int(11) NOT NULL AUTO_INCREMENT,
    Role_Name VARCHAR(50), 
    Created_Date DATE,
    Modified_Date Date,
    PRIMARY KEY (Role_ID, Role_Name)
);

CREATE TABLE `user_mstr` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(50) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  `USER_PASSWORD` varchar(20) NOT NULL,
  `ENABLED` bit(1) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8;

CREATE TABLE DOCTOR_SPECIALITY_MAPPING(
    User_ID INTEGER NOT NULL,
    SPECIALITY_ID INTEGER NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES user_mstr(User_ID),
    PRIMARY KEY (User_ID,SPECIALITY_ID)
);


CREATE TABLE SPECIALITY_INFO(
  SPECIALITY_ID INTEGER NOT NULL AUTO_INCREMENT,
  SPECIALITY VARCHAR(50) NOT NULL,
  PRIMARY KEY (SPECIALITY_ID,SPECIALITY)
);